### PR TITLE
Replace more textures

### PR DESCRIPTION
**Pull request by mildsunrise**
- Replace `mech/computerscreen*.jpg` textures with screenshots grabbed from Wikipedia.
- Replace some very simple textures, with replacements made from scratch in Gimp.
- Some other textures replaced too.

What do you think? @lumidify @gsliepen

### CODE REVIEW

**Comment by lumidify** [comment]
Looks good!

**Comment by gsliepen** [comment]
On Sun, Aug 07, 2016 at 10:17:03AM -0700, Xavier Mendez wrote:

> - Replace `mech/computerscreen*.jpg` textures with screenshots grabbed from Wikipedia.
> - Replace some very simple textures, with replacements made from scratch in Gimp.
> - Some other textures replaced too.
> 
> What do you think? @lumidify @gsliepen 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/perpendicular-dimensions/blobandconquer/pull/4

Very nice! Keep those pull requests coming :)

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by mildsunrise** [comment]
By the way, we are compatible with the GFDL, are we?

**Comment by gsliepen** [comment]
On Sun, Aug 07, 2016 at 12:48:25PM -0700, Xavier Mendez wrote:

> By the way, we are compatible with the GFDL, are we?

It should be fine without the invariant text clause. We're not really
linking with images; we have a game engine and resources it loads.
Otherwise we also wouldn't be able to use any CC-BY-SA licensed work.

That said, now that you got me thinking, it might be a good idea to
avoid GPL and GFDL licensed artwork here, since the source requirement
is difficult to fulfill.

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Pull request merged**
